### ISSUE TITLE
Add API for deposit/withdrawal of stablecoins

### ISSUE THREAD

**Issue by Tom-OriginStorage** [Team-Asparagus/Decentralized-trust-fund#1]
- Add Solidity APIs for deposit & withdrawal of stablecoins
- Support for at least one of the following stablecoins on Mumbai testnet 
     - DAI
     - USDT
     - USDC

**Comment by avwunufe** [comment]
Implemented API for deposit of dai

**Comment by avwunufe** [comment]
Implemented API for withdrawal of dai by owner
