### ISSUE TITLE
Add API stub for Chainlink

### ISSUE THREAD

**Issue by Tom-OriginStorage** [Team-Asparagus/Decentralized-trust-fund#2]
Add a stub API for oracle calls
For example:
- `is_user_alive()` which either returns `true` or `false` and we have a separate function to control what it returns until we implement Chainlink or other oracles

**Comment by avwunufe** [comment]
"Added the Chainlink API stub that mocks the checkupkeep and allows user to call perform upkeep if enough time (interval) has passed and transfers them a predetermined amount of dai"
