### ISSUE TITLE
Add Trustee to Constructor

### ISSUE THREAD

**Issue by Tom-OriginStorage** [Team-Asparagus/Decentralized-trust-fund#3]
Add Trustee to `DecentralizedTrustFund` contract
- There can be more than 1 trustee
- A trustee can also be the beneficiary
- A trustee can control the funds just like the owner and allocate the funds into stable yield generating protocols, but they cannot withdraw the funds

**Comment by avwunufe** [comment]
Added trustee to constructor, included reusable modifiers for trustees 
and owner access and added function for owner to add individual trustee
Close issue #3
